name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Download dependencies
      run: nuget restore $Env:GITHUB_WORKSPACE\KPT.sln
      
    - name: Build
      run: |
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
            .\MSBuild.exe $Env:GITHUB_WORKSPACE\KPT.sln -tv:current
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: KPT-SNAPSHOT-${{ GITHUB_RUN_NUMBER }}
        path: .

