name: Master [onMerge]

on:
  push:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Download dependencies
      run: nuget restore $Env:GITHUB_WORKSPACE\KPT.sln
      
    - name: Build
      run: |
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
            .\MSBuild.exe $Env:GITHUB_WORKSPACE\KPT.sln -t:Build -p:Configuration=Release -tv:current
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: KPT-SNAPSHOT-${{ github.run_number }}
        path: .\bin\Release

